### ISSUE TITLE
[scrum-dice] Socket 연결 해제 Error 해소

### ISSUE THREAD

**Issue by JeongJaeSoon** [2P3S/2p3s-backend-system#30]
```
[Nest] 468  - 06/25/2023, 11:24:11 PM     LOG [ChatGateway] ✅ JI-267SnK_LvObX_AAAF 소켓 연결 성공
[Nest] 468  - 06/25/2023, 11:24:12 PM   ERROR [ChatGateway] 존재하지 않는 방입니다.
[Nest] 468  - 06/25/2023, 11:24:12 PM     LOG [ChatGateway] ❌ JI-267SnK_LvObX_AAAF 소켓 연결 해제

/Users/94soon/dev/project/2p3s-backend-system/src/chat/member/member.service.ts:44
      throw new NotFoundException(`Socket ${socketId} is not found`);
            ^
NotFoundException: Socket JI-267SnK_LvObX_AAAF is not found
    at MemberService.updateMemberDisconnected (/Users/94soon/dev/project/2p3s-backend-system/src/chat/member/member.service.ts:44:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ChatGateway.checkSocket (/Users/94soon/dev/project/2p3s-backend-system/src/chat/chat.gateway.ts:130:20)
    at ChatGateway.handleDisconnect (/Users/94soon/dev/project/2p3s-backend-system/src/chat/chat.gateway.ts:60:20)
```

**Comment by JeongJaeSoon** [comment]
https://github.com/2P3S/2p3s-backend-system/blob/ca44754f4c77ea33efd6d7d7a6cb430958edce29/src/main.ts#L7-L13

**Comment by JeongJaeSoon** [comment]
방 접속 후 새로고침 했을 때, join-requested 로 사용자의 socketId 정보 갱신해주지 않아서 발생하는 듯
* 해당 로직의 예외처리 추가 필요
* 프론트 엔드 로직 구현 시 동작 과정 재 확인 필요 @hyunnnn98

**Comment by JeongJaeSoon** [comment]
resolved at https://github.com/2P3S/2p3s-backend-system/commit/775c74f35fcf1c8487a495a32a4aed1cc78d41be
